[package]
name = "ml-models"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
csv = "1.1"
ndarray = "0.15.3"
rand_distr = "0.4.1"
